def a_funcao_que_vai_gerar_problema(seila, qualquer, coisa):
    print('A funcao problemática ' + seila.title() + ' ' + qualquer.title() + ' ' + coisa.title())

a_funcao_que_vai_gerar_problema()

'''
Este ocorre pq eu chamaei a funcao na linha 4 e não passei o valores 
para o argumento da função.
'''
